name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  java-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile code
        run: mvn clean compile

      - name: Run tests
        run: mvn test